# Generated by Django 5.0 on 2023-12-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=120, unique=True)),
                ('walking', models.CharField(max_length=200)),
                ('running', models.CharField(max_length=200)),
                ('gardening', models.CharField(blank=True, max_length=200, null=True)),
                ('swim', models.CharField(max_length=200)),
                ('tea', models.CharField(blank=True, max_length=200, null=True)),
                ('like', models.CharField(blank=True, max_length=200, null=True)),
                ('tv', models.CharField(blank=True, max_length=200, null=True)),
                ('movie', models.CharField(blank=True, max_length=200, null=True)),
                ('shopping', models.CharField(blank=True, max_length=200, null=True)),
                ('happy', models.CharField(blank=True, max_length=200, null=True)),
                ('errands', models.CharField(blank=True, max_length=200, null=True)),
                ('rides', models.CharField(blank=True, max_length=200, null=True)),
                ('childcare', models.CharField(blank=True, max_length=200, null=True)),
                ('eldercare', models.CharField(blank=True, max_length=200, null=True)),
                ('petcare', models.CharField(blank=True, max_length=200, null=True)),
                ('tutoring', models.CharField(blank=True, max_length=200, null=True)),
                ('home', models.CharField(blank=True, max_length=200, null=True)),
                ('landscape', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('sharePreference', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
